"""Production-style diagnostic charts for GNet9 dynamics."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np


AggregateSeriesSpec = tuple[str, str, str, str, float]
NestedSeriesSpec = tuple[str, tuple[str, ...], float]

APP_COLORS = {
    "RTP_OPUS": "#ef4444",
    "RTP_VLC_AV": "#f97316",
    "FTP_DATA": "#3b82f6",
    "DNS": "#a855f7",
    "RTP_TELEMOST": "#14b8a6",
    "LIVE_HLS": "#eab308",
    "ATTACK_DOS": "#ff1744",
    "ATTACK_DDOS": "#b91c1c",
    "ATTACK_SYN": "#f43f5e",
}
APP_LABELS = {
    "RTP_OPUS": "Голос / Opus",
    "RTP_VLC_AV": "VLC / голос и видео",
    "FTP_DATA": "Файлы / FTP",
    "DNS": "Имена / DNS",
    "RTP_TELEMOST": "Видеоконференция",
    "LIVE_HLS": "Прямая трансляция",
    "ATTACK_DOS": "Атака DoS",
    "ATTACK_DDOS": "Атака DDoS",
    "ATTACK_SYN": "Атака SYN flood",
}

AGGREGATE_SERIES: tuple[AggregateSeriesSpec, ...] = (
    ("sla_margin_min", "L1", "sla_margin", "min", 1.0),
    ("sla_margin_mean", "L1", "sla_margin", "mean", 1.0),
    ("l2_cpu_mean", "L2", "cpu_load_percent", "mean", 1.0),
    ("l2_cpu_max", "L2", "cpu_load_percent", "max", 1.0),
    ("l2_ram_max", "L2", "ram_load_percent", "max", 1.0),
    ("edge_stability_min", "EDGE", "stability_margin", "min", 1.0),
    ("edge_stability_mean", "EDGE", "stability_margin", "mean", 1.0),
    ("edge_loss_max_percent", "EDGE", "loss_probability", "max", 100.0),
)

TRAFFIC_SERIES: tuple[NestedSeriesSpec, ...] = (
    ("packet_count", ("traffic", "summary", "packet_count"), 1.0),
    ("traffic_rate_mbps", ("traffic", "summary", "offered_rate_mbps"), 1.0),
    ("traffic_efficiency_percent", ("traffic", "summary", "protocol_efficiency_ratio"), 100.0),
    ("traffic_mean_latency_ms", ("traffic", "summary", "mean_one_way_latency_ms"), 1.0),
    ("traffic_max_latency_ms", ("traffic", "summary", "max_one_way_latency_ms"), 1.0),
    ("traffic_observed_loss_percent", ("traffic", "summary", "observed_loss_ratio"), 100.0),
)

ARBITRATOR_SERIES: tuple[NestedSeriesSpec, ...] = (
    ("remap_pressure", ("arbitrator", "analysis", "remap_pressure"), 1.0),
    ("lyapunov_value", ("arbitrator", "analysis", "lyapunov_value"), 1.0),
    ("koopman_residual", ("arbitrator", "analysis", "koopman_residual"), 1.0),
    ("decision_confidence", ("arbitrator", "analysis", "decision_confidence"), 1.0),
)

ATTACK_SERIES: tuple[NestedSeriesSpec, ...] = (
    ("attack_active_count", ("attacks", "active_count"), 1.0),
    ("attack_intensity_percent", ("attacks", "maximum_intensity_ratio"), 100.0),
    ("attack_rate_mbps", ("attacks", "attack_rate_mbps"), 1.0),
    ("legitimate_loss_percent", ("attacks", "legitimate_loss_ratio"), 100.0),
    ("legitimate_delivery_percent", ("attacks", "legitimate_delivery_ratio"), 100.0),
    ("impacted_gold_flows", ("attacks", "impacted_gold_flow_count"), 1.0),
    ("gold_sla_compliance_percent", ("attacks", "gold_sla_compliance_ratio"), 100.0),
    ("attack_pressure", ("arbitrator", "analysis", "attack_pressure"), 1.0),
    ("target_utilization_percent", ("attacks", "maximum_target_utilization_percent"), 1.0),
)


def export_dynamics_charts(
    dynamics: dict[str, Any],
    output_dir: Path,
    *,
    model=None,
    flow_snapshots: list[dict[str, Any]] | None = None,
) -> dict[str, Path]:
    """Export a compact non-overlapping set of operational diagnostics."""
    output_dir.mkdir(parents=True, exist_ok=True)
    series = extract_dynamics_chart_series(dynamics)
    application_series = extract_application_series(dynamics)

    charts = {
        "health": output_dir / "dynamics_health.png",
        "traffic": output_dir / "traffic_composition.png",
        "capacity": output_dir / "link_capacity.png",
        "arbitrator": output_dir / "dynamics_arbitrator.png",
        "attacks": output_dir / "dynamics_attacks.png",
    }

    _plot_health_dashboard(series, charts["health"])
    _plot_traffic_composition(series, application_series, charts["traffic"])
    _plot_link_capacity(model, flow_snapshots or dynamics.get("snapshots", []), charts["capacity"])
    _plot_arbitrator(series, charts["arbitrator"])
    _plot_attacks(series, dynamics, charts["attacks"])

    # Generated by older releases and superseded by dynamics_health.png.
    for legacy_name in ("dynamics_sla.png", "dynamics_load_stability.png", "dynamics_traffic.png"):
        (output_dir / legacy_name).unlink(missing_ok=True)
    return charts


def extract_dynamics_chart_series(dynamics: dict[str, Any]) -> dict[str, list[float]]:
    """Extract time series from compact arbitrator and traffic summaries."""
    snapshots = dynamics.get("snapshots", [])
    series_keys = (
        "time_seconds",
        *(name for name, *_ in AGGREGATE_SERIES),
        *(name for name, *_ in TRAFFIC_SERIES),
        *(name for name, *_ in ARBITRATOR_SERIES),
        *(name for name, *_ in ATTACK_SERIES),
    )
    series: dict[str, list[float]] = {key: [] for key in series_keys}
    for snapshot in snapshots:
        series["time_seconds"].append(float(snapshot.get("time_seconds", 0.0)))
        for name, level, metric, statistic, multiplier in AGGREGATE_SERIES:
            series[name].append(_aggregate(snapshot, level, metric, statistic) * multiplier)
        for name, path, multiplier in (*TRAFFIC_SERIES, *ARBITRATOR_SERIES, *ATTACK_SERIES):
            series[name].append(_nested_float(snapshot, path) * multiplier)
    return series


def extract_application_series(dynamics: dict[str, Any]) -> dict[str, dict[str, list[float]]]:
    """Return per-application traffic series available even in summary mode."""
    snapshots = dynamics.get("snapshots", [])
    names = sorted({
        name
        for snapshot in snapshots
        for name in snapshot.get("traffic", {}).get("summary", {}).get("applications", {})
    })
    metrics = (
        "flow_count", "packet_count", "offered_rate_mbps", "protocol_efficiency_ratio",
        "mean_one_way_latency_ms", "max_one_way_latency_ms",
    )
    result = {name: {metric: [] for metric in metrics} for name in names}
    for snapshot in snapshots:
        applications = snapshot.get("traffic", {}).get("summary", {}).get("applications", {})
        for name in names:
            values = applications.get(name, {})
            for metric in metrics:
                result[name][metric].append(float(values.get(metric, 0.0)))
    return result


def _plot_health_dashboard(series: dict[str, list[float]], path: Path) -> None:
    fig, axes = _dashboard("GNet9 · состояние сети", 2, 2, (14, 9))
    time = series["time_seconds"]

    ax = axes[0, 0]
    _plot_line(ax, time, series["sla_margin_min"], "минимальный", "#34d399")
    _plot_line(ax, time, series["sla_margin_mean"], "средний", "#60a5fa")
    ax.axhline(0.60, color="#f87171", linestyle="--", linewidth=1.2, label="порог наблюдения 0,60")
    _style_axes(ax, "Запас SLA абонентов L1", "доля", (0, 1.02))

    ax = axes[0, 1]
    _plot_line(ax, time, series["l2_cpu_mean"], "ЦП: средняя", "#22d3ee")
    _plot_line(ax, time, series["l2_cpu_max"], "ЦП: максимальная", "#60a5fa")
    _plot_line(ax, time, series["l2_ram_max"], "ОЗУ: максимальная", "#c084fc")
    ax.axhline(80.0, color="#f87171", linestyle="--", linewidth=1.2, label="предельная загрузка")
    _style_axes(ax, "Оборудование L2", "%", (0, 100))

    ax = axes[1, 0]
    _plot_line(ax, time, series["edge_stability_min"], "минимальная", "#34d399")
    _plot_line(ax, time, series["edge_stability_mean"], "средняя", "#60a5fa")
    _style_axes(ax, "Устойчивость транспортных связей", "доля", (0, 1.02))

    ax = axes[1, 1]
    _plot_line(ax, time, series["traffic_rate_mbps"], "канальная скорость", "#fbbf24")
    efficiency = series["traffic_efficiency_percent"]
    ax2 = ax.twinx()
    _plot_line(ax2, time, efficiency, "протокольная эффективность", "#a78bfa")
    ax2.set_ylabel("эффективность, %", color="#cbd5e1")
    ax2.tick_params(colors="#cbd5e1")
    ax2.set_ylim(0, 100)
    _style_axes(ax, "Трафик и протокольная эффективность", "Мбит/с")
    _combined_legend(ax, ax2)
    _save(fig, path)


def _plot_traffic_composition(
    series: dict[str, list[float]],
    applications: dict[str, dict[str, list[float]]],
    path: Path,
) -> None:
    fig, axes = _dashboard("GNet9 · профиль сервисного трафика", 2, 2, (14, 9))
    time = series["time_seconds"]
    names = list(applications)

    for name in names:
        color = APP_COLORS.get(name, "#94a3b8")
        label = APP_LABELS.get(name, name)
        _plot_line(axes[0, 0], time, applications[name]["offered_rate_mbps"], label, color)
        _plot_line(axes[0, 1], time, applications[name]["packet_count"], label, color)
    _style_axes(axes[0, 0], "Канальная скорость по приложениям", "Мбит/с")
    _style_axes(axes[0, 1], "Пакеты за один шаг", "пакеты")

    service_names = [name for name in names if not name.startswith("ATTACK_")]
    labels = [APP_LABELS.get(name, name) for name in service_names]
    colors = [APP_COLORS.get(name, "#94a3b8") for name in service_names]
    efficiency = [applications[name]["protocol_efficiency_ratio"][-1] * 100 if applications[name]["protocol_efficiency_ratio"] else 0 for name in service_names]
    axes[1, 0].bar(labels, efficiency, color=colors, width=0.62)
    _style_axes(axes[1, 0], "Доля полезной нагрузки в канальном трафике", "%", (0, 100), legend=False)
    axes[1, 0].tick_params(axis="x", rotation=12)
    _annotate_bars(axes[1, 0], efficiency, "{:.1f}%")

    x = np.arange(len(service_names))
    means = [applications[name]["mean_one_way_latency_ms"][-1] if applications[name]["mean_one_way_latency_ms"] else 0 for name in service_names]
    maxima = [applications[name]["max_one_way_latency_ms"][-1] if applications[name]["max_one_way_latency_ms"] else 0 for name in service_names]
    axes[1, 1].bar(x - 0.18, means, 0.36, color="#38bdf8", label="средняя")
    axes[1, 1].bar(x + 0.18, maxima, 0.36, color="#fb7185", label="максимальная")
    axes[1, 1].set_xticks(x, labels, rotation=12)
    _style_axes(axes[1, 1], "Односторонняя задержка", "мс")
    _save(fig, path)


def _plot_link_capacity(model, snapshots: list[dict[str, Any]], path: Path) -> None:
    fig, axes = _dashboard("GNet9 · фактическая загрузка каналов", 1, 2, (15, 7))
    axes = axes.ravel()
    if model is None:
        for ax in axes:
            ax.text(0.5, 0.5, "модель недоступна", ha="center", va="center", color="#cbd5e1")
        _save(fig, path)
        return

    links = _link_load_rows(model, snapshots)
    top = sorted(links, key=lambda item: item["rate_mbps"], reverse=True)[:15]
    labels = [item["label"] for item in reversed(top)]
    rates = [item["rate_mbps"] for item in reversed(top)]
    utilizations = [item["utilization_percent"] for item in reversed(top)]
    colors = [item["color"] for item in reversed(top)]

    axes[0].barh(labels, rates, color=colors)
    _style_axes(axes[0], "15 наиболее нагруженных связей", "Мбит/с", legend=False)
    axes[1].barh(labels, utilizations, color=colors)
    _style_axes(axes[1], "Использование доступной ёмкости", "% ёмкости", legend=False)
    for index, value in enumerate(utilizations):
        axes[1].text(value, index, f" {value:.3f}%", va="center", color="#e2e8f0", fontsize=8)
    _save(fig, path)


def _plot_arbitrator(series: dict[str, list[float]], path: Path) -> None:
    fig, axes = _dashboard("GNet9 · L7 контроль устойчивости", 1, 2, (15, 6.5))
    remap_ax, signals_ax = axes.ravel()
    time = series["time_seconds"]
    _plot_line(remap_ax, time, series["remap_pressure"], "давление переназначения", "#f87171")
    remap_ax.axhline(0.20, color="#fbbf24", linewidth=1.3, linestyle="--", label="порог планирования переназначения")
    remap_top = min(1.02, max(0.30, max(series["remap_pressure"], default=0.0) * 1.10))
    _style_axes(remap_ax, "Необходимость переназначения", "нормированное значение", (0, remap_top))
    remap_ax.set_xlabel("время, с", color="#cbd5e1")

    _plot_line(signals_ax, time, series["decision_confidence"], "уверенность решения", "#34d399")
    _plot_line(signals_ax, time, series["lyapunov_value"], "показатель Ляпунова", "#60a5fa")
    _plot_line(signals_ax, time, series["koopman_residual"], "невязка Купмана", "#c084fc")
    _style_axes(signals_ax, "Диагностические сигналы L7", "нормированное значение", (0, 1.02))
    signals_ax.set_xlabel("время, с", color="#cbd5e1")
    _save(fig, path)


def _plot_attacks(series: dict[str, list[float]], dynamics: dict[str, Any], path: Path) -> None:
    fig, axes = _dashboard("GNet9 · воздействие MITRE ATT&CK", 2, 2, (15, 9))
    time = series["time_seconds"]

    ax = axes[0, 0]
    _plot_line(ax, time, series["attack_intensity_percent"], "интенсивность", "#fb7185")
    _plot_line(ax, time, [value * 100.0 for value in series["attack_pressure"]], "давление на арбитратор", "#fbbf24")
    _plot_line(ax, time, series["target_utilization_percent"], "оценка загрузки цели", "#c084fc")
    _style_axes(ax, "Активность атаки", "%", (0, 105))

    ax = axes[0, 1]
    _plot_line(ax, time, series["attack_rate_mbps"], "вредоносная канальная скорость", "#ef4444")
    _style_axes(ax, "Интенсивность вредоносного трафика", "Мбит/с")

    ax = axes[1, 0]
    _plot_line(ax, time, series["legitimate_delivery_percent"], "доставлено", "#34d399")
    _plot_line(ax, time, series["legitimate_loss_percent"], "потеряно", "#f87171")
    _style_axes(ax, "Качество легитимного трафика", "% пакетов", (0, 105))

    ax = axes[1, 1]
    _plot_line(ax, time, series["gold_sla_compliance_percent"], "Gold в пределах SLA", "#fbbf24")
    ax2 = ax.twinx()
    _plot_line(ax2, time, series["impacted_gold_flows"], "затронутые Gold-потоки", "#c084fc")
    ax2.set_ylabel("потоки", color="#cbd5e1")
    ax2.tick_params(colors="#cbd5e1")
    _style_axes(ax, "Приоритетные Gold-потоки", "% соответствия SLA", (0, 105))
    _combined_legend(ax, ax2)
    for axis in axes.ravel():
        axis.set_xlabel("время, с", color="#cbd5e1")
    for index, window in enumerate(_attack_windows(dynamics)):
        color = ("#ef4444", "#b91c1c", "#f43f5e")[index % 3]
        for axis in axes.ravel():
            axis.axvspan(window["start"], window["end"], color=color, alpha=0.08, zorder=0)
        axes[0, 0].text(
            (window["start"] + window["end"]) / 2.0, 103.0, window["label"],
            ha="center", va="bottom", color="#fecaca", fontsize=8, fontweight="bold",
        )
    _save(fig, path)


def _attack_windows(dynamics: dict[str, Any]) -> list[dict[str, Any]]:
    grouped: dict[str, dict[str, Any]] = {}
    step_seconds = float(dynamics.get("config", {}).get("step_seconds", 1.0))
    for snapshot in dynamics.get("snapshots", []):
        for event in snapshot.get("attacks", {}).get("events", []):
            item = grouped.setdefault(event["attack_id"], {
                "start": float(snapshot.get("time_seconds", 0.0)),
                "end": float(snapshot.get("time_seconds", 0.0)) + step_seconds,
                "label": {"dos": "DoS", "ddos": "DDoS", "syn_flood": "SYN flood"}.get(event.get("kind"), event["attack_id"]),
            })
            item["end"] = max(item["end"], float(snapshot.get("time_seconds", 0.0)) + step_seconds)
    return list(grouped.values())


def _link_load_rows(model, snapshots: list[dict[str, Any]]) -> list[dict[str, Any]]:
    peak_bytes: dict[frozenset[str], int] = {}
    interval_by_edge: dict[frozenset[str], int] = {}
    for snapshot in snapshots:
        flows = snapshot.get("traffic", {}).get("flows", [])
        current: dict[frozenset[str], int] = {}
        for flow in flows:
            interval = int(flow.get("interval_seconds", 1))
            for source, target in zip(flow.get("route", []), flow.get("route", [])[1:]):
                edge = frozenset((source, target))
                current[edge] = current.get(edge, 0) + int(flow.get("wire_bytes", 0))
                interval_by_edge[edge] = interval
        for edge, wire_bytes in current.items():
            peak_bytes[edge] = max(peak_bytes.get(edge, 0), wire_bytes)

    rows = []
    for edge, wire_bytes in peak_bytes.items():
        source, target = sorted(edge)
        capacity = float(model.graph.edges[source, target].get("capacity_mbps", 0.0))
        rate = wire_bytes * 8.0 / max(interval_by_edge.get(edge, 1), 1) / 1_000_000.0
        roles = {model.graph.nodes[node].get("role") for node in edge}
        color = "#22d3ee" if "mobile-subscriber" in roles else "#fbbf24" if "fixed-subscriber" in roles else "#60a5fa"
        rows.append({
            "label": f"{source} ↔ {target}",
            "rate_mbps": rate,
            "utilization_percent": rate / max(capacity, 1e-9) * 100.0,
            "color": color,
        })
    return rows


def _dashboard(title: str, rows: int, columns: int, size: tuple[float, float]):
    fig, axes = plt.subplots(rows, columns, figsize=size, squeeze=False)
    fig.suptitle(title, color="#f8fafc", fontsize=18, fontweight="bold", y=0.98)
    _dark_figure(fig, axes)
    return fig, axes


def _dark_figure(fig, axes) -> None:
    fig.patch.set_facecolor("#0f172a")
    for ax in np.asarray(axes).flat:
        ax.set_facecolor("#111827")


def _plot_line(ax, x, y, label: str, color: str) -> None:
    ax.plot(x, y, marker="o", markersize=4, linewidth=2.1, color=color, label=label)


def _style_axes(ax, title: str, ylabel: str, ylim=None, *, legend: bool = True) -> None:
    ax.set_title(title, color="#f8fafc", fontsize=12.5, fontweight="bold", pad=10)
    ax.set_ylabel(ylabel, color="#cbd5e1")
    ax.tick_params(colors="#cbd5e1")
    for spine in ax.spines.values():
        spine.set_color("#334155")
    ax.grid(True, axis="y", color="#334155", linewidth=0.7, alpha=0.65)
    ax.set_axisbelow(True)
    if ylim is not None:
        ax.set_ylim(*ylim)
    if legend:
        ax.legend(loc="best", facecolor="#172033", edgecolor="#475569", labelcolor="#e2e8f0", fontsize=8)


def _combined_legend(ax, ax2) -> None:
    handles1, labels1 = ax.get_legend_handles_labels()
    handles2, labels2 = ax2.get_legend_handles_labels()
    ax.get_legend().remove()
    ax.legend(handles1 + handles2, labels1 + labels2, loc="best", facecolor="#172033", edgecolor="#475569", labelcolor="#e2e8f0", fontsize=8)


def _annotate_bars(ax, values: list[float], pattern: str) -> None:
    for index, value in enumerate(values):
        ax.text(index, value + max(values or [1]) * 0.025, pattern.format(value), ha="center", color="#e2e8f0", fontsize=9)


def _save(fig, path: Path) -> None:
    fig.tight_layout(rect=(0, 0, 1, 0.95))
    fig.savefig(path, dpi=180, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close(fig)


def _aggregate(snapshot: dict[str, Any], level: str, metric: str, statistic: str) -> float:
    values = snapshot.get("arbitrator", {}).get("level_metric_aggregates", {}).get(level, {}).get("metrics", {}).get(metric, {})
    return float(values.get(statistic, 0.0))


def _nested_float(source: dict[str, Any], path: tuple[str, ...]) -> float:
    value: Any = source
    for key in path:
        if not isinstance(value, dict):
            return 0.0
        value = value.get(key, {})
    return float(value or 0.0)
